### ISSUE TITLE
antd-mobile 的问题

### ISSUE THREAD

**Issue by xiaoyinsss** [xlsdg/dva-antd-mobile-starter#6]
在做的时候,一直尝试定制主题,但是一直不成功,我使用的是theme.js的方法  不知道您有么有尝试过定制主题

**Comment by xlsdg** [comment]
没有定制过主题，可以去 `antd-mobile` 的官方仓库去提问。

**Comment by GGBO0M** [comment]
问一下 用了这个后 所有 import 引入进来的class 类 都会 加上一段hash  那我怎么修改 antd-mobile 的样式  我写的样式类名 都会加上一段 hash

**Comment by xlsdg** [comment]
使用：

``` less
:global {
    .xxxx {
        color: #fff;
    }
}
```
